#Requires -RunAsAdministrator
$ErrorActionPreference = "Stop"
$InstallRoot = "C:\Sovereign"
$LogDir = "$InstallRoot\logs"
if (-not (Test-Path $LogDir)) { New-Item -ItemType Directory -Path $LogDir -Force | Out-Null }
function Write-Log($msg) { $ts = Get-Date -Format "HH:mm:ss"; $line = "[$ts] $msg"; Write-Host $line -ForegroundColor Cyan; Add-Content -Path "$LogDir\deploy.log" -Value $line -EA SilentlyContinue }
function Refresh-Path { $env:Path = [System.Environment]::GetEnvironmentVariable("Path","Machine") + ";" + [System.Environment]::GetEnvironmentVariable("Path","User") }
function Install-Git { if (Get-Command git -EA SilentlyContinue) { Write-Log "Git: $(git --version)"; return }; Write-Log "Downloading Git..."; $url = "https://github.com/git-for-windows/git/releases/download/v2.43.0.windows.1/Git-2.43.0-64-bit.exe"; $out = "$env:TEMP\git.exe"; Invoke-WebRequest -Uri $url -OutFile $out -UseBasicParsing; Start-Process $out "/VERYSILENT /NORESTART /SP-" -Wait; Refresh-Path; Write-Log "Git installed." }
function Install-Node { if (Get-Command node -EA SilentlyContinue) { Write-Log "Node: $(node --version)"; return }; Write-Log "Downloading Node.js..."; $url = "https://nodejs.org/dist/v20.11.1/node-v20.11.1-x64.msi"; $out = "$env:TEMP\node.msi"; Invoke-WebRequest -Uri $url -OutFile $out -UseBasicParsing; Start-Process "msiexec.exe" "/i $out /qn /norestart" -Wait; Refresh-Path; Write-Log "Node installed." }
function Install-Python { if (Get-Command python -EA SilentlyContinue) { Write-Log "Python: $(python --version)"; return }; Write-Log "Downloading Python..."; $url = "https://www.python.org/ftp/python/3.12.2/python-3.12.2-amd64.exe"; $out = "$env:TEMP\py.exe"; Invoke-WebRequest -Uri $url -OutFile $out -UseBasicParsing; Start-Process $out "/quiet InstallAllUsers=1 PrependPath=1 Include_test=0" -Wait; Refresh-Path; Write-Log "Python installed." }
function Install-PM2 { if (Get-Command pm2 -EA SilentlyContinue) { Write-Log "PM2 already installed."; return }; Write-Log "Installing PM2..."; npm install -g pm2; Refresh-Path; Write-Log "PM2 installed." }
Write-Host "`n=== SOVEREIGN OS 9 VR DEPLOYER ===" -ForegroundColor Green
Install-Git; Install-Node; Install-Python; Install-PM2
$Repos = @("sovereign-os-9-core","cbdc-mantis-engine","destiny-custody-bridge","tsl-ledger-interface","aegentis-vr-backend","genesis-moment-renderer","agentic-ai-orchestrator","sovereign-dashboard-react")
$GitHubUser = "shalominattii-us"
foreach ($repo in $Repos) { $path = "$InstallRoot\$repo"; if (Test-Path "$path\.git") { Write-Log "Pulling $repo..."; Set-Location $path; git fetch origin; git reset --hard origin/main 2>$null; if ($LASTEXITCODE -ne 0) { git reset --hard origin/master 2>$null } } else { Write-Log "Cloning $repo..."; git clone "https://github.com/$GitHubUser/$repo.git" $path --depth 1 } }
$builds = @{ "sovereign-dashboard-react" = { npm install; npm run build 2>$null }; "aegentis-vr-backend" = { npm install }; "genesis-moment-renderer" = { npm install; npm run build 2>$null }; "agentic-ai-orchestrator" = { if (Test-Path requirements.txt) { python -m pip install -r requirements.txt --quiet 2>$null }; if (Test-Path package.json) { npm install } }; "destiny-custody-bridge" = { if (Test-Path package.json) { npm install }; if (Test-Path requirements.txt) { python -m pip install -r requirements.txt --quiet 2>$null } }; "tsl-ledger-interface" = { if (Test-Path package.json) { npm install }; if (Test-Path requirements.txt) { python -m pip install -r requirements.txt --quiet 2>$null } }; "cbdc-mantis-engine" = { if (Test-Path package.json) { npm install }; if (Test-Path requirements.txt) { python -m pip install -r requirements.txt --quiet 2>$null } } }
foreach ($repo in $builds.Keys) { $rpath = "$InstallRoot\$repo"; if (-not (Test-Path $rpath)) { continue }; Write-Log "Building $repo..."; Set-Location $rpath; Invoke-Command $builds[$repo] }
$secret = -join ((65..90)+(97..122)+(48..57) | Get-Random -Count 64 | ForEach-Object { [char]$_ })
@"`nSOVEREIGN_ROOT=$InstallRoot`nSOVEREIGN_JWT_SECRET=$secret`nXRPL_NODE=wss://s1.ripple.com`nTSL_LEDGER=TSL_MAIN`nESC_ISSUER=rYourESCIssuerAddressHere`nVR_PORT=7777`nVR_HOST=0.0.0.0`nDASHBOARD_PORT=3000`nAGENTIC_PORT=8844`nAGENTIC_RUNTIME=hybrid`nGENTIS_MODEL_PATH=$InstallRoot\agentic-ai-orchestrator\models`nDESTINY_PORT=9229`nLEGACY_AUTO_WRAP=true`n"@ | Out-File "$InstallRoot\.env.sovereign" -Encoding utf8 -Force
Write-Log "Environment config written."
foreach ($port in @(7777,8844,3000,9229)) { $name = "Sovereign-Port-$port"; if (-not (Get-NetFirewallRule -DisplayName $name -EA SilentlyContinue)) { New-NetFirewallRule -DisplayName $name -Direction Inbound -Protocol TCP -LocalPort $port -Action Allow | Out-Null; Write-Log "Port $port opened." } }
$eco = @"`nmodule.exports = {`n  apps: [`n    { name: 'aegentis-vr', script: '$($InstallRoot.Replace('\','\\'))\\aegentis-vr-backend\\vr-server.js', env: { NODE_ENV: 'production', PORT: 7777 }, log_file: '$($InstallRoot.Replace('\','\\'))\\logs\\vr.log', autorestart: true },`n    { name: 'sovereign-dashboard', script: '$($InstallRoot.Replace('\','\\'))\\sovereign-dashboard-react\\server.js', env: { PORT: 3000, STATIC_PATH: '$($InstallRoot.Replace('\','\\'))\\sovereign-dashboard-react\\build' }, log_file: '$($InstallRoot.Replace('\','\\'))\\logs\\dashboard.log', autorestart: true },`n    { name: 'agentic-ai', script: '$($InstallRoot.Replace('\','\\'))\\agentic-ai-orchestrator\\main.py', interpreter: 'python', env: { PORT: 8844 }, log_file: '$($InstallRoot.Replace('\','\\'))\\logs\\agentic.log', autorestart: true },`n    { name: 'destiny-bridge', script: '$($InstallRoot.Replace('\','\\'))\\destiny-custody-bridge\\index.js', env: { PORT: 9229 }, log_file: '$($InstallRoot.Replace('\','\\'))\\logs\\destiny.log', autorestart: true }`n  ]`n};`n"@
$eco | Out-File "$InstallRoot\ecosystem.config.js" -Encoding utf8 -Force
pm2 delete all 2>$null; pm2 start "$InstallRoot\ecosystem.config.js"; pm2 save; pm2 startup windows --install 2>$null; if ($LASTEXITCODE -ne 0) { Write-Log "PM2 startup already set." }
Start-Sleep 5
foreach ($svc in @(@{N="VR";U="http://localhost:7777/rooms"},@{N="Dashboard";U="http://localhost:3000"},@{N="Agentic";U="http://localhost:8844/health"})) { try { Invoke-RestMethod $svc.U -TimeoutSec 5 -EA Stop | Out-Null; Write-Log "$($svc.N): ONLINE" } catch { Write-Log "$($svc.N): STARTING..." } }
Write-Host "`nDEPLOYED." -ForegroundColor Green; Write-Host "Dashboard: http://localhost:3000" -ForegroundColor Yellow; Write-Host "VR: http://localhost:7777" -ForegroundColor Yellow; Write-Host "Agentic: http://localhost:8844" -ForegroundColor Yellow; Write-Host "Logs: $LogDir" -ForegroundColor Yellow